package constant

const (
	MAX_ALLOWANCE_DONATION_DEDUCT = 100000.0
	
	MIN_ALLOWANCE_PERSONAL = 10001.0
	MAX_ALLOWANCE_PERSONAL = 100000.0

	MIN_ALLOWANCE_K_RECEIPT = 1.0
	MAX_ALLOWANCE_K_RECEIPT = 100000.0

)

const (
	DEDUCT_PERSONAL_ID = "personal"
	DEDUCT_K_RECEIPT_ID = "k-receipt" 
	DEDUCT_DONATION_ID = "donation"
)


